DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS SHOPS CASCADE;




CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
); 

CREATE TABLE SHOPS(
  ID SERIAL PRIMARY KEY NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  LATITUDE numeric,
  LONGITUDE numeric,
  ADDRESS VARCHAR(100),
  PHONE VARCHAR(30),
  IMAGE VARCHAR(255),
  RATING VARCHAR(100),
  PRICE VARCHAR(30),
  HOURS VARCHAR(1000),
  IMAGES VARCHAR(1000),
  CATEGORY VARCHAR(250)
);



